[package]
name = "modeling"
version = "0.1.0"
authors = ["go"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "*"
winit = "*"
cgmath = "*"
env_logger = "*"
log = "*"
wgpu = "*"
futures = "*"
bytemuck = { version = "*", features = ["derive"] }
anyhow = "*"
tobj = "*"

[build-dependencies]
anyhow = "*"
fs_extra = "*"
glob = "*"
shaderc = "*"