[package]
name = "modeling"
version = "0.1.0"
authors = ["go"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "*"
winit = { version = "*", features = ["web-sys"] }
cgmath = "*"
env_logger = "*"
log = "*"
wgpu = "*"
futures = { version = "*", features = ["thread-pool"] }
bytemuck = { version = "*", features = ["derive"] }
anyhow = "*"
tobj = "*"
gltf = { version = "*", features = ["utils", "names"] }
itertools = "*"
rayon = "*"
tokio = { version = "*", features = ["full"] }


[build-dependencies]
anyhow = "*"
fs_extra = "*"
glob = "*"
rayon = "*"
shaderc = "*"


[dev-dependencies]
log = "*"
