[package]
name = "modeling"
version = "0.1.0"
authors = ["go"]
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
thiserror = "*"
structopt = "*"
itertools = "*"
env_logger = "*"

chrono = "0.4"
log = "*"
futures = { version = "*", features = ["thread-pool"] }

rayon = "*"
tokio = { version = "*", features = ["full"] }

image = "*"
tobj = "*"
cgmath = "*"
gltf = { version = "*", features = ["utils", "names"] }

winit = { version = "*", features = ["web-sys"] }
wgpu = "*"
bytemuck = { version = "*", features = ["derive"] }

egui = "*"
egui_wgpu_backend = "*"
#egui_wgpu_backend = { path = "../egui_wgpu_backend" }
egui_winit_platform = "*"
epi = "*"
egui_demo_lib = "*"


[build-dependencies]
anyhow = "*"
fs_extra = "*"
glob = "*"
rayon = "*"
shaderc = "*"


[dev-dependencies]
log = "*"
